name: Release Terrakube

on: 
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: New Issue
      run: |
        echo "Issue just created"
    - uses: stefanbuck/github-issue-parser@v3
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/bug.yml
    
    - run: cat ${HOME}/issue-parser-result.json

    - run: echo $FAVORITE_DISH
      env:
        FAVORITE_DISH: ${{ steps.issue-parser.outputs.issueparser_favorite_dish }}

    - run: echo $JSON_STRING > output.json
      env:
        JSON_STRING: ${{ steps.issue-parser.outputs.jsonString }}

    - name: New Issue
      run: |
        git config --global user.email "example@example.com"
        git config --global user.name "example"
        git branch newBranch main
        git checkout newBranch
        echo "#Hello World" > hello.md
        git status
        git add hello.md
        git commit -m "Sample Hello World"
        git push

    - name: create pull request
      run: gh pr create -B newBranch -H main --title 'Merge newBranch into main' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
